// client/src/lib/audit/AuditRegistry.ts
// Centralized Registry for Enterprise Audit Logging (Modules, Actions, Severity)

export const AuditModules = {
  AUTHENTICATION: "AUTHENTICATION",
  SECURITY: "SECURITY",
  USERS: "USERS",
  ROLES: "ROLES",
  PERMISSIONS: "PERMISSIONS",
  BILLING: "BILLING",
  SALES: "SALES",
  INVOICES: "INVOICES",
  RETURNS: "RETURNS",
  EXCHANGES: "EXCHANGES",
  CUSTOMERS: "CUSTOMERS",
  SUPPLIERS: "SUPPLIERS",
  PURCHASES: "PURCHASES",
  INVENTORY: "INVENTORY",
  PRODUCTS: "PRODUCTS",
  STOCK: "STOCK",
  BARCODE: "BARCODE",
  HUID: "HUID",
  METAL: "METAL",
  METAL_EXCHANGE: "METAL_EXCHANGE",
  METAL_RATES: "METAL_RATES",
  PAYMENTS: "PAYMENTS",
  GST: "GST",
  BRANCHES: "BRANCHES",
  SETTINGS: "SETTINGS",
  INTEGRATIONS: "INTEGRATIONS",
  RFID: "RFID",
  BACKUP: "BACKUP",
  AUDIT: "AUDIT",
  REPORTS: "REPORTS",
} as const;

export type AuditModuleType = keyof typeof AuditModules | string;

export const AuditActions = {
  // Authentication & Security
  LOGIN_SUCCESS: "SECURITY.LOGIN_SUCCESS",
  LOGIN_FAILED: "SECURITY.LOGIN_FAILED",
  LOGIN_BLOCKED: "SECURITY.LOGIN_BLOCKED",
  LOGOUT: "SECURITY.LOGOUT",
  PASSWORD_CHANGED: "SECURITY.PASSWORD_CHANGED",
  PASSWORD_RESET: "SECURITY.PASSWORD_RESET",
  TWO_FACTOR_ENABLED: "SECURITY.2FA_ENABLED",
  TWO_FACTOR_DISABLED: "SECURITY.2FA_DISABLED",
  TWO_FACTOR_VERIFIED: "SECURITY.2FA_VERIFIED",
  TWO_FACTOR_FAILED: "SECURITY.2FA_FAILED",
  RECOVERY_CODE_USED: "SECURITY.RECOVERY_CODE_USED",
  RECOVERY_CODES_REGENERATED: "SECURITY.RECOVERY_CODES_REGENERATED",
  IP_WHITELIST_ADDED: "SECURITY.IP_WHITELIST_ADDED",
  IP_WHITELIST_REMOVED: "SECURITY.IP_WHITELIST_REMOVED",
  IP_WHITELIST_MODIFIED: "SECURITY.IP_WHITELIST_MODIFIED",
  IP_ACCESS_BLOCKED: "SECURITY.IP_ACCESS_BLOCKED",
  SESSION_CREATED: "SECURITY.SESSION_CREATED",
  SESSION_REVOKED: "SECURITY.SESSION_REVOKED",
  ALL_SESSIONS_REVOKED: "SECURITY.ALL_SESSIONS_REVOKED",
  SECURITY_POLICY_CHANGED: "SECURITY.POLICY_CHANGED",

  // Billing & Sales
  INVOICE_CREATED: "BILLING.INVOICE_CREATED",
  INVOICE_UPDATED: "BILLING.INVOICE_UPDATED",
  INVOICE_CANCELLED: "BILLING.INVOICE_CANCELLED",
  INVOICE_RETURNED: "BILLING.INVOICE_RETURNED",
  INVOICE_EXCHANGED: "BILLING.INVOICE_EXCHANGED",
  INVOICE_DISCOUNT_CHANGED: "BILLING.DISCOUNT_CHANGED",
  INVOICE_NUMBER_GENERATED: "BILLING.INVOICE_NUMBER_GENERATED",

  // Inventory, Products & Stock
  PRODUCT_CREATED: "INVENTORY.PRODUCT_CREATED",
  PRODUCT_UPDATED: "INVENTORY.PRODUCT_UPDATED",
  PRODUCT_DELETED: "INVENTORY.PRODUCT_DELETED",
  STOCK_ADJUSTED: "INVENTORY.STOCK_ADJUSTED",
  STOCK_TRANSFERRED: "INVENTORY.STOCK_TRANSFERRED",
  STOCK_RECEIVED: "INVENTORY.STOCK_RECEIVED",
  STOCK_ISSUED: "INVENTORY.STOCK_ISSUED",
  STOCK_RESERVED: "INVENTORY.STOCK_RESERVED",
  STOCK_RELEASED: "INVENTORY.STOCK_RELEASED",

  // HUID & Barcode
  HUID_ASSIGNED: "HUID.HUID_ASSIGNED",
  HUID_CHANGED: "HUID.HUID_CHANGED",
  BARCODE_GENERATED: "BARCODE.BARCODE_GENERATED",
  BARCODE_REGENERATED: "BARCODE.BARCODE_REGENERATED",
  BARCODE_DEACTIVATED: "BARCODE.BARCODE_DEACTIVATED",

  // Metal & Metal Exchange
  METAL_RECEIVED: "METAL.METAL_RECEIVED",
  METAL_ISSUED: "METAL.METAL_ISSUED",
  METAL_ADJUSTED: "METAL.METAL_ADJUSTED",
  METAL_RATE_CHANGED: "METAL.RATE_CHANGED",
  PURITY_CHANGED: "METAL.PURITY_CHANGED",
  METAL_SESSION_OPENED: "METAL.SESSION_OPENED",
  METAL_SESSION_CLOSED: "METAL.SESSION_CLOSED",
  METAL_EXCHANGE_CREATED: "METAL.EXCHANGE_CREATED",
  METAL_EXCHANGE_UPDATED: "METAL.EXCHANGE_UPDATED",
  METAL_EXCHANGE_CLOSED: "METAL.EXCHANGE_CLOSED",

  // Payments & Financials
  PAYMENT_CREATED: "PAYMENTS.PAYMENT_CREATED",
  PAYMENT_UPDATED: "PAYMENTS.PAYMENT_UPDATED",
  PAYMENT_REVERSED: "PAYMENTS.PAYMENT_REVERSED",
  REFUND_CREATED: "PAYMENTS.REFUND_CREATED",
  REFUND_REVERSED: "PAYMENTS.REFUND_REVERSED",

  // Users & Permissions
  USER_CREATED: "USERS.USER_CREATED",
  USER_UPDATED: "USERS.USER_UPDATED",
  USER_DISABLED: "USERS.USER_DISABLED",
  USER_ENABLED: "USERS.USER_ENABLED",
  ROLE_ASSIGNED: "USERS.ROLE_ASSIGNED",
  ROLE_CHANGED: "USERS.ROLE_CHANGED",
  PERMISSION_CHANGED: "USERS.PERMISSION_CHANGED",

  // Settings & System
  SETTINGS_UPDATED: "SETTINGS.SETTINGS_UPDATED",
  INTEGRATIONS_CONFIGURED: "SETTINGS.INTEGRATIONS_CONFIGURED",
  AUDIT_LOG_EXPORTED: "AUDIT.LOG_EXPORTED",
  AUDIT_RETENTION_UPDATED: "AUDIT.RETENTION_UPDATED",
} as const;

export type AuditActionType = (typeof AuditActions)[keyof typeof AuditActions] | string;

export const AuditSeverity = {
  INFO: "INFO",
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
} as const;

export type AuditSeverityType = keyof typeof AuditSeverity;

export const AuditStatus = {
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  BLOCKED: "BLOCKED",
  DENIED: "DENIED",
  PENDING: "PENDING",
} as const;

export type AuditStatusType = keyof typeof AuditStatus;
