import { NextRequest, NextResponse } from "next/server";
import { prisma } from "../../../../../../libs/prisma";
import { jsPDF } from "jspdf";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { branchId, dateFrom, dateTo } = body;

    const parsedBranchId = parseInt(branchId || "0");
    if (!parsedBranchId) {
      return NextResponse.json({ error: "branchId is required" }, { status: 400 });
    }

    // Fetch branch info
    const branch = await prisma.branch.findUnique({
      where: { id: parsedBranchId }
    });
    if (!branch) {
      return NextResponse.json({ error: "Branch not found" }, { status: 404 });
    }

    // Fetch company settings
    const settings = await prisma.companySettings.findFirst() || {
      companyName: "AURUM ERP",
      requireHuidForSales: false,
    };

    // Fetch invoices in date range
    const dateFilter: any = {};
    if (dateFrom) dateFilter.gte = new Date(dateFrom);
    if (dateTo) {
      const end = new Date(dateTo);
      end.setHours(23, 59, 59, 999);
      dateFilter.lte = end;
    }

    const invoices = await prisma.invoice.findMany({
      where: {
        branchId: parsedBranchId,
        ...(Object.keys(dateFilter).length > 0 ? { createdAt: dateFilter } : {}),
      },
      include: {
        customer: true,
        items: {
          include: {
            product: {
              include: {
                subCategory: {
                  include: {
                    category: true
                  }
                }
              }
            }
          }
        }
      },
      orderBy: { createdAt: "asc" }
    });

    // Create PDF document
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4"
    });

    const companyName = settings.companyName || "AURUM ERP";
    const timestamp = new Date().toLocaleString("en-IN");
    const periodStr = `${dateFrom ? new Date(dateFrom).toLocaleDateString("en-IN") : "Start"} to ${dateTo ? new Date(dateTo).toLocaleDateString("en-IN") : "End"}`;

    const addFooter = (pageNo: number) => {
      doc.setFont("Helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(120);
      doc.text(`Generated by ${companyName} | ${timestamp}`, 15, 287);
      doc.text(`Page ${pageNo}`, 190, 287, { align: "right" });
    };

    // ──────────────── PAGE 1: COVER PAGE ────────────────
    doc.setFillColor(10, 10, 11); // Dark background
    doc.rect(0, 0, 210, 297, "F");

    doc.setTextColor(201, 148, 58); // Gold color
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(28);
    doc.text("AURUM", 105, 80, { align: "center" });

    doc.setFontSize(22);
    doc.setTextColor(240, 235, 224);
    doc.text("GST COMPLIANCE REPORT", 105, 110, { align: "center" });

    doc.setFont("Helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(150, 150, 150);
    doc.text(`Period: ${periodStr}`, 105, 125, { align: "center" });
    doc.text(`Branch: ${branch.name}`, 105, 133, { align: "center" });

    // Branch Details Box
    doc.setDrawColor(201, 148, 58);
    doc.setLineWidth(0.5);
    doc.rect(30, 160, 150, 50);

    doc.setFontSize(10);
    doc.setTextColor(200, 200, 200);
    doc.text(`Address: ${branch.address}, ${branch.city}`, 35, 175);
    doc.text(`State: ${branch.state} - ${branch.pincode}`, 35, 185);
    doc.text(`GSTIN: ${branch.email || "N/A"}`, 35, 195); // using branch email or fallback since branch has no gstin field

    addFooter(1);

    // ──────────────── PAGE 2: B2C SUMMARY TABLE ────────────────
    doc.addPage();
    doc.setFillColor(255, 255, 255); // White background for print ease
    doc.rect(0, 0, 210, 297, "F");

    doc.setTextColor(0, 0, 0);
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(16);
    doc.text("B2C Summary Report", 15, 25);
    doc.setFontSize(10);
    doc.setFont("Helvetica", "normal");
    doc.text(`Taxable supply details for unregistered customers. Period: ${periodStr}`, 15, 32);

    // Group items by HSN Code
    const hsnSummary: Record<string, { desc: string; taxable: number; cgst: number; sgst: number }> = {
      "7113": { desc: "Gold Jewellery", taxable: 0, cgst: 0, sgst: 0 },
      "7114": { desc: "Articles of gold", taxable: 0, cgst: 0, sgst: 0 },
      "7117": { desc: "Imitation Jewellery", taxable: 0, cgst: 0, sgst: 0 },
    };

    for (const inv of invoices) {
      if (inv.customer.gstin) continue; // Skip B2B for this page
      for (const item of inv.items) {
        const cat = item.product.subCategory.category.name.toLowerCase();
        let hsn = "7113";
        if (cat.includes("imitation")) hsn = "7117";
        else if (cat.includes("article") || cat.includes("utensil")) hsn = "7114";

        const itemTaxable = item.totalBeforeTax;
        const itemCgst = item.cgst;
        const itemSgst = item.sgst;

        hsnSummary[hsn].taxable += itemTaxable;
        hsnSummary[hsn].cgst += itemCgst;
        hsnSummary[hsn].sgst += itemSgst;
      }
    }

    // Draw Table Headers
    let y = 45;
    doc.setFillColor(240, 240, 240);
    doc.rect(15, y, 180, 8, "F");
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(9);
    doc.text("HSN", 18, y + 6);
    doc.text("Description", 45, y + 6);
    doc.text("Taxable Value", 95, y + 6, { align: "right" });
    doc.text("CGST (1.5%)", 130, y + 6, { align: "right" });
    doc.text("SGST (1.5%)", 160, y + 6, { align: "right" });
    doc.text("Total", 192, y + 6, { align: "right" });

    // Table Content
    doc.setFont("Helvetica", "normal");
    y += 8;
    for (const [hsn, data] of Object.entries(hsnSummary)) {
      if (data.taxable === 0) continue;
      doc.line(15, y, 195, y);
      doc.text(hsn, 18, y + 6);
      doc.text(data.desc, 45, y + 6);
      doc.text(`INR ${data.taxable.toFixed(0)}`, 95, y + 6, { align: "right" });
      doc.text(`INR ${data.cgst.toFixed(0)}`, 130, y + 6, { align: "right" });
      doc.text(`INR ${data.sgst.toFixed(0)}`, 160, y + 6, { align: "right" });
      const total = data.taxable + data.cgst + data.sgst;
      doc.text(`INR ${total.toFixed(0)}`, 192, y + 6, { align: "right" });
      y += 8;
    }
    doc.line(15, y, 195, y);

    addFooter(2);

    // ──────────────── PAGE 3: B2B INVOICE LIST ────────────────
    doc.addPage();
    doc.setFillColor(255, 255, 255);
    doc.rect(0, 0, 210, 297, "F");

    doc.setTextColor(0, 0, 0);
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(16);
    doc.text("B2B Invoice List", 15, 25);
    doc.setFontSize(10);
    doc.setFont("Helvetica", "normal");
    doc.text(`Supplies to registered customers (with GSTIN). Period: ${periodStr}`, 15, 32);

    const b2bInvoices = invoices.filter((inv: any) => inv.customer.gstin && inv.customer.gstin.trim().length > 0);

    y = 45;
    doc.setFillColor(240, 240, 240);
    doc.rect(15, y, 180, 8, "F");
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(8);
    doc.text("Invoice No", 17, y + 6);
    doc.text("Date", 42, y + 6);
    doc.text("Customer / GSTIN", 68, y + 6);
    doc.text("Taxable", 125, y + 6, { align: "right" });
    doc.text("CGST", 147, y + 6, { align: "right" });
    doc.text("SGST", 169, y + 6, { align: "right" });
    doc.text("Total Amount", 192, y + 6, { align: "right" });

    doc.setFont("Helvetica", "normal");
    y += 8;

    if (b2bInvoices.length === 0) {
      doc.text("No B2B invoices recorded in this period.", 105, y + 10, { align: "center" });
    } else {
      for (const inv of b2bInvoices) {
        if (y > 260) {
          addFooter(3);
          doc.addPage();
          y = 30;
          doc.setFillColor(240, 240, 240);
          doc.rect(15, y, 180, 8, "F");
          doc.setFont("Helvetica", "bold");
          doc.text("Invoice No", 17, y + 6);
          doc.text("Date", 42, y + 6);
          doc.text("Customer / GSTIN", 68, y + 6);
          doc.text("Taxable", 125, y + 6, { align: "right" });
          doc.text("CGST", 147, y + 6, { align: "right" });
          doc.text("SGST", 169, y + 6, { align: "right" });
          doc.text("Total Amount", 192, y + 6, { align: "right" });
          doc.setFont("Helvetica", "normal");
          y += 8;
        }

        doc.line(15, y, 195, y);
        doc.text(inv.invoiceNumber, 17, y + 5);
        doc.text(new Date(inv.createdAt).toLocaleDateString("en-IN"), 42, y + 5);
        doc.text(`${inv.customer.name.slice(0,18)}\nGSTIN: ${inv.customer.gstin}`, 68, y + 4);
        const taxable = inv.totalMetalAmount + inv.totalMakingAmount + inv.totalStoneAmount;
        doc.text(taxable.toFixed(0), 125, y + 5, { align: "right" });
        doc.text(inv.cgst.toFixed(0), 147, y + 5, { align: "right" });
        doc.text(inv.sgst.toFixed(0), 169, y + 5, { align: "right" });
        doc.text(inv.totalAmount.toFixed(0), 192, y + 5, { align: "right" });
        y += 8;
      }
      doc.line(15, y, 195, y);
    }

    addFooter(b2bInvoices.length > 0 && y > 260 ? 4 : 3);

    const pdfBuffer = doc.output("arraybuffer");
    return new NextResponse(pdfBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="GST_Report_${periodStr.replace(/ /g, "")}.pdf"`
      }
    });

  } catch (error: any) {
    console.error("PDF generation failed:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate PDF GST report" },
      { status: 500 }
    );
  }
}
